baseurl: "" # The subpath of your site. Use "" if you're hosting a blog at the root level.
url: "singhmanmeet.com" # the base hostname & protocol for your site.
title: "Manmeet Singh"
email: "manmeet3 (at) gmail.com"
paginate: 10 #articles per page
paginate_path: /posts/page:num #makes pagination working

#contacts
git: "https://github.com/manmeet3"  #your github url here.
stackoverflow: "http://stackoverflow.com/users/3969732/manmeet-singh" #Add your stackoverflow url here.
twitter: "https://twitter.com/_manmeet3"  #Add your twitter url here.
linkedin: "https://www.linkedin.com/in/msingh16"
steam: "https://steamcommunity.com/id/manmeet3/"

markdown: kramdown

#disqus comment
disqus:
    shortname: "test" #your disqus comment short name

#google analytics
google:
    tracking-id: "" #your tracking id here

gems:
  - jekyll-sitemap
  - jekyll-paginate

# This is used by feed.xml. Uncomment if you want to use it.
# description: "..."

exclude:
  - "README.md"
  - "CHANGELOG.md"
  - "Gemfile"
  - "Gemfile.lock"

permalink: /posts/:title

defaults:
  -
    scope:
      path: ""
      type: "pages"
    values:
      layout: "default"
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
